[package]
name = "unicode_box_drawing_wfc"
version = "0.1.0"
edition = "2021"

[dependencies]
bitflags = "2.3.1"
rand = "0.8"
term_size = "0.3.2"
tiled_wfc = { path = "/Users/josh/projects/tiled_wfc" }
